# Generated by Django 3.2.9 on 2021-11-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='lines',
            field=models.TextField(),
        ),
    ]
