# Generated by Django 3.2.9 on 2021-11-26 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_poem_linecount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poem',
            name='user',
        ),
    ]
